### ISSUE TITLE
I configure canal HA , How to configure the syncClinet ?

### ISSUE THREAD

**Issue by Hackeruncle** [sasou/syncClient#1]
I configure canal HA , how to configure the syncClinet ? or not support ?

**Comment by sasou** [comment]
设置好配置文件，直接运行：sh start.sh，就可以启动bin 下已经打包好的jar进程；自己编译：可以用eclipse将src代码export出runnable jar file；

**Comment by xuxu0728** [comment]
你好，打扰了，canal新手，有个问题请教一下，运行了canal的ｄｅｓｔｉｎａｔｉｏn是ｅｘａｍｐｌｅ，怎么知道是否传入到kafka中呢？

**Comment by sasou** [comment]
你好，可以用kafka只带的tool脚本 kafka-console-consumer.sh 查看kafka topic：
创建的topic名称规则是：数据库名_表名，比如数据库demo的user表： demo_user

**Comment by xuxu0728** [comment]
你好～想请教一下
这个适用于单机部署的canal吗？

**Comment by Hackeruncle** [comment]
Thanks fro @sasou .
