### ISSUE TITLE
是否对canal到kafka的吞吐量做过统计？

### ISSUE THREAD

**Issue by V-I-C-T-O-R** [sasou/syncClient#5]
将mysql准实时订阅到kafka，保证数据不丢失。
请问在kafka producer发送到kafka ack=all的情况下，大概发送消息的吞吐量是多少？

**Comment by sasou** [comment]
没做过kafka的吞吐量测试，redis做过（参考意义不大）

**Comment by V-I-C-T-O-R** [comment]
－_－，了解。保证绝对不丢数据的话，这边吞吐量保持几百条每秒(消息大小一般几百k)，哎

**Comment by sasou** [comment]
你每条消息太大了，可以考虑增加多个canal

**Comment by hiliuxg** [comment]
mysql数据做update和delete操作，kafka的数据你怎么处理
