### ISSUE TITLE
能解释一下kafka.target_deep参数吗

### ISSUE THREAD

**Issue by Fanduzi** [sasou/syncClient#7]
比较菜没看懂, 就看到kafka.target_deep=4的意思 ,请问还有几个值呢?分别是什么作用?

**Comment by sasou** [comment]
target_deep是topic名称的规则，比如：target_deep=4，数据库的每个表有单独的topic，比如数据库admin的user表，对应的kafka主题名为：sync_admin_user；
值 1，名称规则：sync_{项目名}_{db}_{table}; 
值 2，名称规则：sync_{项目名}_{db};
值 3，名称规则：sync_{项目名}; 
值 4，名称规则：sync_{db}_{table};
